/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainComponent.Controls;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Rectangle;
import mainComponent.GameMainFrame;

/**
 *
 * @author Administrator
 */
public class RectControl extends javax.swing.JPanel implements ChangeListener {

    /**
     * Creates new form RectControl
     */
    private SliderControl x, y, width, height;
    private Rectangle rectangle;

    public RectControl(String name, Rectangle rectangle, int maxWidth, int maxHeight) {
        initComponents();
        this.rectangle = rectangle;

        setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        x = new SliderControl("X", rectangle.x, -maxWidth, maxWidth, 1);
        y = new SliderControl("Y", rectangle.y, -maxHeight, maxHeight, 1);
        width = new SliderControl("Width", rectangle.width, 0, maxWidth, 1);
        height = new SliderControl("Height", rectangle.height, 0, maxWidth, 1);
        x.SetChangeListener(this);
        y.SetChangeListener(this);
        width.SetChangeListener(this);
        height.SetChangeListener(this);
        Dimension size = new Dimension(x.getPreferredSize().width * 2 + 10, x.getPreferredSize().height * 2 + 30);
        setSize(size);
        setPreferredSize(size);
        this.add(x);
        this.add(y);
        this.add(width);
        this.add(height);
        setBorder(javax.swing.BorderFactory.createTitledBorder(name));

    }

    public static RectControl createAndShow(String name, Rectangle rectangle, int maxWidth, int maxHeight) {
        RectControl rc = new RectControl(name, rectangle, maxWidth, maxHeight);
        GameMainFrame.controlPanel.add(rc);
        return rc;
    }

    public void setRectangle(Rectangle rectangle) {

        this.rectangle = rectangle;

        x.setValue(rectangle.x);
        y.setValue(rectangle.y);
        width.setValue(rectangle.width);
        height.setValue(rectangle.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void onChange(SliderControl source, float newValue) {
        if (source == x) {
            rectangle.x = (int) newValue;
        } else if (source == y) {
            rectangle.y = (int) newValue;
        } else if (source == width) {
            rectangle.width = (int) newValue;
        } else if (source == height) {
            rectangle.height = (int) newValue;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
